apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}-deployment
        image: "{{ .Values.image }}:{{ .Values.tag}}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.port.service }}
